services:
  web:
    build:
      context: .
      dockerfile: docker/apache-php.Dockerfile
    volumes:
      - ./silverstripe:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      SS_DATABASE_SERVER: db
      SS_DATABASE_NAME: silverstripe
      SS_DATABASE_USERNAME: silverstripe
      SS_DATABASE_PASSWORD: silverstripe

  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: silverstripe
      MYSQL_USER: silverstripe
      MYSQL_PASSWORD: silverstripe
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
